version: "3.8"

services:
  vpn:
    container_name: vpn
    build: .
    privileged: true
    restart: unless-stopped
    ports:
      - "18082:8000"
      - "23389:3389"
      - "22443:443"
    environment:
      - RDP_TARGET=192.168.3.1
      - HTTPS_TARGET=192.168.4.1
    volumes:
      - "./:/etc/wireguard/config:ro"

